### PR TITLE
Add SignIn, SignOut route

### PR DESCRIPTION
**Pull request by agus-wesly**
- [x] Sign in route
- [x] Sign out route

### CODE REVIEW

**Review by mhaidarhanif — CHANGES_REQUESTED** [review]
Need to format all the files using Prettier

**Review by mhaidarhanif — CHANGES_REQUESTED** [review]
Also just remove both `async` keyword and `// eslint-disable-next-line require-await` to resolve the warning

**Comment by agus-wesly** [comment]
> Need to format all the files using Prettier

Im running `pnpm check:prettier`&`pnpm fix:prettier` to resolve this problem in the next commit. Is that enough ?

**Comment by mhaidarhanif** [comment]
> Im running `pnpm check:prettier`&`pnpm fix:prettier` to resolve this problem in the next commit. Is that enough ?

Yes

**Review by mhaidarhanif — APPROVED** [review]
Can be merged

But just as mentioned in https://github.com/bandungdevcom/bandungdev.com/issues/2 because auth-related routes will be plenty of changes, next can focus on non-auth issues.

**Pull request merged**
